//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Input/StandarControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @StandarControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @StandarControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""StandarControls"",
    ""maps"": [
        {
            ""name"": ""GameplayControls"",
            ""id"": ""9120f1a3-a930-4c5a-abcc-ead33fc8c4e4"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""00ef905f-b896-45f6-8050-4b7a01b2b106"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Button"",
                    ""id"": ""995cff47-157b-48a5-9238-6f09c21aac9b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_00"",
                    ""type"": ""Button"",
                    ""id"": ""40b949f3-61b9-4129-96ed-5da4d351ee73"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_1"",
                    ""type"": ""Button"",
                    ""id"": ""071c1d3a-cb9c-4abd-97a2-b4bc6d81332d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_2"",
                    ""type"": ""Button"",
                    ""id"": ""61ca99f7-e731-4fcb-b06f-d4885af58b62"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_3"",
                    ""type"": ""Button"",
                    ""id"": ""6cb18a48-b11c-4017-bd56-e8d4d333767b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_4"",
                    ""type"": ""Button"",
                    ""id"": ""1215e792-6ab0-4e81-85fa-c73b18af39c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_5"",
                    ""type"": ""Button"",
                    ""id"": ""ad98890a-808b-4493-a3be-60509ee00441"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_6"",
                    ""type"": ""Button"",
                    ""id"": ""fefd5665-0db1-4f05-8237-bd15e7b3373e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8857f199-7a07-4150-b7d9-0df1014c5a30"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c8251eb-c1b8-4fc2-ba3f-93f08c89730c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7af051dd-a93f-4f0d-bb5c-2ee726d4c0ef"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_00"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7127bb42-746a-461c-8e70-976f7501c8d5"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b92c8052-2248-4945-a2f1-c52d629b718f"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a671841-482f-4ba9-9d48-f60aa8533d19"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a04ff02-885b-4241-9df9-f339453e210a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3c3f2c7-0cf8-407b-bfdd-36901810e2a7"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8e50b1c-502c-4608-abb6-a8731468abb2"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameplayControls
        m_GameplayControls = asset.FindActionMap("GameplayControls", throwIfNotFound: true);
        m_GameplayControls_Move = m_GameplayControls.FindAction("Move", throwIfNotFound: true);
        m_GameplayControls_Look = m_GameplayControls.FindAction("Look", throwIfNotFound: true);
        m_GameplayControls_Action_00 = m_GameplayControls.FindAction("Action_00", throwIfNotFound: true);
        m_GameplayControls_Action_1 = m_GameplayControls.FindAction("Action_1", throwIfNotFound: true);
        m_GameplayControls_Action_2 = m_GameplayControls.FindAction("Action_2", throwIfNotFound: true);
        m_GameplayControls_Action_3 = m_GameplayControls.FindAction("Action_3", throwIfNotFound: true);
        m_GameplayControls_Action_4 = m_GameplayControls.FindAction("Action_4", throwIfNotFound: true);
        m_GameplayControls_Action_5 = m_GameplayControls.FindAction("Action_5", throwIfNotFound: true);
        m_GameplayControls_Action_6 = m_GameplayControls.FindAction("Action_6", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameplayControls
    private readonly InputActionMap m_GameplayControls;
    private List<IGameplayControlsActions> m_GameplayControlsActionsCallbackInterfaces = new List<IGameplayControlsActions>();
    private readonly InputAction m_GameplayControls_Move;
    private readonly InputAction m_GameplayControls_Look;
    private readonly InputAction m_GameplayControls_Action_00;
    private readonly InputAction m_GameplayControls_Action_1;
    private readonly InputAction m_GameplayControls_Action_2;
    private readonly InputAction m_GameplayControls_Action_3;
    private readonly InputAction m_GameplayControls_Action_4;
    private readonly InputAction m_GameplayControls_Action_5;
    private readonly InputAction m_GameplayControls_Action_6;
    public struct GameplayControlsActions
    {
        private @StandarControls m_Wrapper;
        public GameplayControlsActions(@StandarControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_GameplayControls_Move;
        public InputAction @Look => m_Wrapper.m_GameplayControls_Look;
        public InputAction @Action_00 => m_Wrapper.m_GameplayControls_Action_00;
        public InputAction @Action_1 => m_Wrapper.m_GameplayControls_Action_1;
        public InputAction @Action_2 => m_Wrapper.m_GameplayControls_Action_2;
        public InputAction @Action_3 => m_Wrapper.m_GameplayControls_Action_3;
        public InputAction @Action_4 => m_Wrapper.m_GameplayControls_Action_4;
        public InputAction @Action_5 => m_Wrapper.m_GameplayControls_Action_5;
        public InputAction @Action_6 => m_Wrapper.m_GameplayControls_Action_6;
        public InputActionMap Get() { return m_Wrapper.m_GameplayControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayControlsActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayControlsActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Action_00.started += instance.OnAction_00;
            @Action_00.performed += instance.OnAction_00;
            @Action_00.canceled += instance.OnAction_00;
            @Action_1.started += instance.OnAction_1;
            @Action_1.performed += instance.OnAction_1;
            @Action_1.canceled += instance.OnAction_1;
            @Action_2.started += instance.OnAction_2;
            @Action_2.performed += instance.OnAction_2;
            @Action_2.canceled += instance.OnAction_2;
            @Action_3.started += instance.OnAction_3;
            @Action_3.performed += instance.OnAction_3;
            @Action_3.canceled += instance.OnAction_3;
            @Action_4.started += instance.OnAction_4;
            @Action_4.performed += instance.OnAction_4;
            @Action_4.canceled += instance.OnAction_4;
            @Action_5.started += instance.OnAction_5;
            @Action_5.performed += instance.OnAction_5;
            @Action_5.canceled += instance.OnAction_5;
            @Action_6.started += instance.OnAction_6;
            @Action_6.performed += instance.OnAction_6;
            @Action_6.canceled += instance.OnAction_6;
        }

        private void UnregisterCallbacks(IGameplayControlsActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Action_00.started -= instance.OnAction_00;
            @Action_00.performed -= instance.OnAction_00;
            @Action_00.canceled -= instance.OnAction_00;
            @Action_1.started -= instance.OnAction_1;
            @Action_1.performed -= instance.OnAction_1;
            @Action_1.canceled -= instance.OnAction_1;
            @Action_2.started -= instance.OnAction_2;
            @Action_2.performed -= instance.OnAction_2;
            @Action_2.canceled -= instance.OnAction_2;
            @Action_3.started -= instance.OnAction_3;
            @Action_3.performed -= instance.OnAction_3;
            @Action_3.canceled -= instance.OnAction_3;
            @Action_4.started -= instance.OnAction_4;
            @Action_4.performed -= instance.OnAction_4;
            @Action_4.canceled -= instance.OnAction_4;
            @Action_5.started -= instance.OnAction_5;
            @Action_5.performed -= instance.OnAction_5;
            @Action_5.canceled -= instance.OnAction_5;
            @Action_6.started -= instance.OnAction_6;
            @Action_6.performed -= instance.OnAction_6;
            @Action_6.canceled -= instance.OnAction_6;
        }

        public void RemoveCallbacks(IGameplayControlsActions instance)
        {
            if (m_Wrapper.m_GameplayControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayControlsActions @GameplayControls => new GameplayControlsActions(this);
    public interface IGameplayControlsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnAction_00(InputAction.CallbackContext context);
        void OnAction_1(InputAction.CallbackContext context);
        void OnAction_2(InputAction.CallbackContext context);
        void OnAction_3(InputAction.CallbackContext context);
        void OnAction_4(InputAction.CallbackContext context);
        void OnAction_5(InputAction.CallbackContext context);
        void OnAction_6(InputAction.CallbackContext context);
    }
}
